title: 'BitDevs Vancouver'
tagline: 'BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Calendar', url: '/calendar'}
  - {name: 'Map', url: '/map'}
  - {name: 'Events', url: 'https://luma.com/vanbitcoin', external: true}
  - {name: 'Cities', url: '/cities'}
